import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.caixa}>
          <div className={styles.linha}>
            <div className={styles.entradaLetra}>
              <input type="text" className={styles.inputLetra} maxlength="1"></input>
            </div>
            <div className={styles.entradaLetra}>
              <input type="text" className={styles.inputLetra} maxlength="1"></input>
            </div>
            <div className={styles.entradaLetra}>
              <input type="text" className={styles.inputLetra} maxlength="1"></input>
            </div>
            <div className={styles.entradaLetra}>
              <input type="text" className={styles.inputLetra} maxlength="1"></input>
            </div>
            <div className={styles.entradaLetra}>
              <input type="text" className={styles.inputLetra} maxlength="1"></input>
            </div>
          </div>
          <div className={styles.linha}>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
          </div>
          <div className={styles.linha}>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
          </div>
          <div className={styles.linha}>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
            <div className={styles.entradaLetraOff}>
              <input type="text" className={styles.inputLetraOff} maxlength="1" disabled></input>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
